blank_issues_enabled: false
contact_links:
  - name: Официальный SmartTube
    url: https://github.com/yuliskov/SmartTube/issues
    about: Ошибки, не связанные с VOT, следует проверять в основном проекте SmartTube.
